apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-appointment-postgres-pvc
  namespace: hospital
  labels:
    app: ms-appointment-postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce        # Un solo pod accede al volumen (suficiente para una BD)
  resources:
    requests:
      storage: 1Gi         # Ajustar en producción
  # storageClassName: standard  ← descomenta si Minikube no elige automáticamente
